[package]
name = "monitor"
version = "0.1.0"
authors = ["Alex Helfet <alex.helfet@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.7"
gdk = "0.13.2"
gio = "0.9.1"
glib = "0.10.0"
gtk = "0.9.0"
log = "0.4.11"
notify-rust = "4"
rt-graph = "0.3.2"
subprocess = "0.2.6"
